### PR TITLE
Exports and rpc method impls

### PR DESCRIPTION
**Pull request by ChikinDeveloper**
* export base58encode/decode
* Use String signer (instead of Ed25519HDKeyPair) for :
-- InstructionListExt.getAccountsWithOptionalFeePayer
-- Message.debug
-- Message.compileut
* Add getSignaturesForAddress to RPCClient

### CODE REVIEW

**Comment by ChikinDeveloper** [comment]
Need these changes in order to build over your library

**Comment by antoineherzog** [comment]
Thank you to contribute to the library!
@ChikinDeveloper the test are failing. Can you check?
Also please be aware that we are about to finalize a big PR to implement all RPC methods here:
https://github.com/cryptoplease/cryptoplease-dart/pull/118
Any feedback is welcome as well! 
@iharobCP will check and tell you what is the process to have this PR include it on master.

**Comment by ChikinDeveloper** [comment]
You are welcome! Im on it
Ok I will check that!

**Comment by antoineherzog** [comment]
@ChikinDeveloper your PR will be merged today or tomorow into Master. Thank you for your support!

**Comment by antoineherzog** [comment]
We are closing this PR in favor of #120 that will land into master today or tomorrow

**Pull request closed without merging**
