### PR TITLE
close token account address

### PR DESCRIPTION
**Pull request by ArjLab**

### CODE REVIEW

**Comment by antoineherzog** [comment]
thank you for your contribution!
@ArjLab test are not passing.
Can you add a test and make them pass?
thank you!

**Comment by ArjLab** [comment]
Now it works properly

**Comment by ArjLab** [comment]
@antoineherzog passed the tests. What's wrong this time?

**Comment by ookami-kb** [comment]
@ArjLab formatting is wrong. Check these 2 files:

```
[solana]: Changed lib/src/programs/token_program/token_instruction.dart
[solana]: Changed test/solana_client_test.dart
```

Use default dart formatter for proper formatting.

**Comment by iharob** [comment]
This PR is not needed as we have this method [here](https://github.com/cryptoplease/cryptoplease-dart/pull/142). Plesae lets try to merge PRs sooner because people are using the library and it is still missing some features.

**Comment by antoineherzog** [comment]
Sure closing in favor #142 
@ookami-kb you need to review it :)

**Pull request closed without merging**
